'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { CEODigest } from '@/types/ceoDigest';
import { BriefingSkeleton } from '../ui/Skeleton';
import { EmptyState } from '../ui/EmptyState';
import { showToast } from '@/components/ui/ToastProvider';

export function CeoDigestWidget() {
  const [digest, setDigest] = useState<CEODigest | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    async function fetchDigest() {
      try {
        // const token = localStorage.getItem('token');
        const res = await fetch('/api/ai/ceo-digest', {
           // headers: { 'Authorization': `Bearer ${token}` }
        });
        if (res.ok) {
           const data = await res.json();
           if (data.success) {
             setDigest(data.data);
           }
        }
      } catch (e) {
        console.error("Failed to fetch CEO digest widget", e);
        showToast.error("Failed to load Executive Briefing", "AI service may be temporarily unavailable.");
      } finally {
        setLoading(false);
      }
    }

    fetchDigest();
  }, []);

  if (loading) {
    return <BriefingSkeleton />;
  }

  // Fallback if no digest available yet
  if (!digest) {
     return (
        <EmptyState 
          title="Daily Executive Briefing"
          description="Generate your first AI briefing to see key insights, simplified metrics, and operational risks here."
          icon={<span className="material-symbols-outlined text-4xl text-slate-300">smart_toy</span>}
          action={
            <Link href="/dashboard/ai-hub" className="px-4 py-2 bg-indigo-600 text-white rounded-lg text-sm font-medium hover:bg-indigo-700 shadow-lg shadow-indigo-600/20 transition-all">
              Go to AI Hub
            </Link>
          }
          className="w-full bg-white dark:bg-[#151c2b] border-slate-200 dark:border-slate-800"
        />
     );
  }

  // Extract key metrics for display
  const revenueAmount = digest.financial.revenue.yesterdayTotal;
  const revenueTarget = digest.financial.revenue.dailyTarget || 1;
  const revenuePercent = digest.financial.revenue.achievementPercent;
  
  const pendingTasks = digest.operational.customerHealth.openTickets + 
                       digest.productivity.strategicProjects.filter(p => p.status === 'at-risk').length;

  const topTrend = digest.risks.anomalies.length > 0 
      ? digest.risks.anomalies[0].affectedArea 
      : 'Operations Stable';
      
  const topTrendAmount = digest.risks.anomalies.length > 0
      ? digest.risks.anomalies[0].severity
      : 'Normal';

  return (
    <div className="w-full relative group">
      {/* Glow Effect behind the card */}
      <div className="absolute -inset-0.5 bg-gradient-to-r from-[#135bec] to-indigo-600 rounded-xl blur opacity-20 group-hover:opacity-40 transition duration-1000 group-hover:duration-200"></div>
      <div className="relative w-full rounded-xl bg-white dark:bg-[#151c2b] border border-slate-200 dark:border-slate-800 shadow-xl overflow-hidden flex flex-col md:flex-row">
        
        {/* Left: The Narrative & Context */}
        <div className="flex-1 p-6 md:p-8 flex flex-col justify-between gap-6">
          <div>
            <div className="flex items-center justify-between mb-2">
              <div className="flex items-center gap-2">
                <div className="p-1.5 rounded-lg bg-gradient-to-br from-indigo-500 to-[#135bec] text-white shadow-lg shadow-[#135bec]/25">
                  <span className="material-symbols-outlined text-[20px] block">auto_awesome</span>
                </div>
                <h3 className="text-lg font-bold text-slate-900 dark:text-white tracking-tight">Morning Briefing</h3>
              </div>
              <div className="flex items-center gap-1.5 text-xs font-medium text-slate-400 dark:text-slate-500 bg-slate-100 dark:bg-slate-800/50 px-2 py-1 rounded-md border border-slate-200 dark:border-slate-700/50">
                <span className="material-symbols-outlined text-[14px] text-[#135bec]">smart_toy</span>
                Generated by Gemini • Today
              </div>
            </div>
            <div className="prose prose-slate dark:prose-invert max-w-none">
              <p className="text-slate-600 dark:text-slate-300 text-lg md:text-xl leading-relaxed font-medium line-clamp-3">
                "Good Morning, Executive. {digest.briefingMessage.split('\n')[2] || "Business operations are consistent with weekly targets."}"
              </p>
            </div>
          </div>
          <div className="flex flex-col sm:flex-row gap-4 pt-4">
            <Link href="/dashboard/ai-hub" className="inline-flex items-center justify-center gap-2 px-5 py-3 bg-[#135bec] hover:bg-[#135bec]/90 text-white text-sm font-bold rounded-lg transition-all shadow-lg shadow-[#135bec]/20 group/btn">
              <span>View Full Analysis</span>
              <span className="material-symbols-outlined text-[18px] group-hover/btn:translate-x-1 transition-transform">arrow_forward</span>
            </Link>
          </div>
        </div>

        {/* Right: The Metrics (Visual Reinforcement) */}
        <div className="w-full md:w-80 bg-slate-50 dark:bg-[#111722]/50 border-t md:border-t-0 md:border-l border-slate-200 dark:border-slate-800 p-6 md:p-8 flex flex-col gap-6 justify-center">
          {/* Metric 1: Revenue */}
          <div className="flex items-start justify-between group/metric cursor-default">
            <div className="flex flex-col">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">Total Revenue</p>
              <p className="text-2xl font-bold text-slate-900 dark:text-white">
                Rp {(revenueAmount / 1000000).toFixed(1)}M
              </p>
            </div>
            <div className={`flex items-center px-2 py-0.5 rounded text-xs font-bold ${revenuePercent >= 100 ? 'text-emerald-500 bg-emerald-500/10' : 'text-amber-500 bg-amber-500/10'}`}>
              <span className="material-symbols-outlined text-[16px]">{revenuePercent >= 100 ? 'trending_up' : 'trending_flat'}</span>
              <span className="ml-1">{revenuePercent}%</span>
            </div>
          </div>
          <div className="w-full h-px bg-slate-200 dark:bg-slate-800"></div>
          
          {/* Metric 2: Anomalies / Risks */}
          <div className="flex items-start justify-between group/metric cursor-default">
            <div className="flex flex-col">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">Top Anomaly</p>
              <p className="text-xl font-bold text-slate-900 dark:text-white truncate max-w-[150px]" title={topTrend}>{topTrend}</p>
            </div>
            <div className="flex items-center text-rose-500 bg-rose-500/10 px-2 py-0.5 rounded text-xs font-bold uppercase">
               {topTrendAmount}
            </div>
          </div>
          <div className="w-full h-px bg-slate-200 dark:bg-slate-800"></div>
          
          {/* Metric 3: Pending Tasks */}
          <div className="flex items-start justify-between group/metric cursor-default">
            <div className="flex flex-col">
              <p className="text-xs font-semibold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1">Action Items</p>
              <p className="text-2xl font-bold text-slate-900 dark:text-white">{pendingTasks} Pending</p>
            </div>
            <div className="size-8 rounded-full bg-amber-500/10 flex items-center justify-center text-amber-500">
              <span className="material-symbols-outlined text-[20px]">priority_high</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
